#!/bin/sh
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE USER IF NOT EXISTS '${TARGET_READONLY_USER}'@'%' IDENTIFIED BY '${TARGET_READONLY_PASSWORD}';
GRANT SELECT, SHOW VIEW ON sample_store.* TO '${TARGET_READONLY_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
